CREATE TABLE public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    title character varying(255) NOT NULL,
    message text NOT NULL,
    type character varying(50) NOT NULL,
    target_type character varying(50) NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY[
        'SYSTEM'::character varying,
        'ADMIN_MESSAGE'::character varying,
        'PRICE_ALERT'::character varying,
        'SECURITY'::character varying,
        'ANNOUNCEMENT'::character varying
    ])::text[]))),
    CONSTRAINT notifications_target_type_check CHECK (((target_type)::text = ANY ((ARRAY[
        'USER'::character varying,
        'BROADCAST'::character varying
    ])::text[])))
);

CREATE INDEX idx_notifications_user_created_at ON public.notifications (user_id, created_at DESC);
CREATE INDEX idx_notifications_user_is_read ON public.notifications (user_id, is_read);

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk_notifications_created_by FOREIGN KEY (created_by) REFERENCES public.users(id);
