CREATE TABLE public.notification_reads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id bigint NOT NULL,
    user_id bigint NOT NULL,
    read_at timestamp(6) without time zone NOT NULL
);

CREATE UNIQUE INDEX uk_notification_reads_notification_user
    ON public.notification_reads (notification_id, user_id);

CREATE INDEX idx_notification_reads_user_id
    ON public.notification_reads (user_id);

ALTER TABLE ONLY public.notification_reads
    ADD CONSTRAINT fk_notification_reads_notification
        FOREIGN KEY (notification_id) REFERENCES public.notifications(id);

ALTER TABLE ONLY public.notification_reads
    ADD CONSTRAINT fk_notification_reads_user
        FOREIGN KEY (user_id) REFERENCES public.users(id);
