CREATE TABLE public.user_moderation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    status character varying(50) NOT NULL,
    reason text,
    blocked_until timestamp(6) without time zone,
    created_by bigint,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT user_moderation_status_check CHECK (((status)::text = ANY ((ARRAY[
        'ACTIVE'::character varying,
        'TEMP_BLOCKED'::character varying,
        'PERM_BLOCKED'::character varying
    ])::text[])))
);

CREATE INDEX idx_user_moderation_user_created_at
    ON public.user_moderation (user_id, created_at DESC);

ALTER TABLE ONLY public.user_moderation
    ADD CONSTRAINT fk_user_moderation_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.user_moderation
    ADD CONSTRAINT fk_user_moderation_created_by FOREIGN KEY (created_by) REFERENCES public.users(id);
