CREATE TABLE public.admin_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id bigint,
    target_user_id bigint,
    action character varying(100) NOT NULL,
    description text,
    metadata text,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT admin_audit_logs_action_check CHECK (((action)::text = ANY ((ARRAY[
        'USER_ACTIVATED'::character varying,
        'USER_DEACTIVATED'::character varying,
        'USER_ROLE_CHANGED'::character varying,
        'USER_TEMP_BLOCKED'::character varying,
        'USER_PERM_BLOCKED'::character varying,
        'USER_UNBLOCKED'::character varying,
        'NOTIFICATION_SENT_TO_USER'::character varying,
        'NOTIFICATION_BROADCAST_SENT'::character varying
    ])::text[])))
);

CREATE INDEX idx_admin_audit_logs_created_at
    ON public.admin_audit_logs (created_at DESC);

CREATE INDEX idx_admin_audit_logs_actor_user_id
    ON public.admin_audit_logs (actor_user_id);

CREATE INDEX idx_admin_audit_logs_target_user_id
    ON public.admin_audit_logs (target_user_id);
