CREATE TABLE public.alerts (
    target_price numeric(19,4) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    triggered_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    condition_type character varying(255) NOT NULL,
    instrument_code character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT alerts_condition_type_check CHECK (((condition_type)::text = ANY ((ARRAY['ABOVE'::character varying, 'BELOW'::character varying])::text[]))),
    CONSTRAINT alerts_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'TRIGGERED'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE public.alerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.news (
    importance_score integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    published_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone NOT NULL,
    language character varying(10),
    region_scope character varying(20) NOT NULL,
    related_symbol character varying(30),
    category character varying(100),
    provider character varying(100) NOT NULL,
    source character varying(100) NOT NULL,
    external_id character varying(200) NOT NULL,
    title character varying(500) NOT NULL,
    url character varying(1200) NOT NULL,
    image_url text,
    summary text
);

ALTER TABLE public.news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.portfolio_holdings (
    buy_price numeric(19,4) NOT NULL,
    quantity numeric(19,4) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    portfolio_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    instrument_code character varying(255) NOT NULL
);

ALTER TABLE public.portfolio_holdings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolio_holdings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.portfolios (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    visibility_status character varying(30) NOT NULL,
    portfolio_name character varying(255) NOT NULL
);

ALTER TABLE public.portfolios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_login_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone NOT NULL,
    role character varying(20) NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    keycloak_id character varying(255),
    preferred_language character varying(255),
    theme_preference character varying(255),
    CONSTRAINT users_preferred_language_check CHECK (((preferred_language)::text = ANY ((ARRAY['TR'::character varying, 'EN'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT users_theme_preference_check CHECK (((theme_preference)::text = ANY ((ARRAY['LIGHT'::character varying, 'DARK'::character varying, 'SYSTEM'::character varying])::text[])))
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.watchlist (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    instrument_code character varying(255) NOT NULL
);

ALTER TABLE public.watchlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watchlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.market_instruments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol character varying(32) NOT NULL,
    display_name character varying(255) NOT NULL,
    instrument_type character varying(50) NOT NULL,
    source character varying(50) NOT NULL,
    currency character varying(10) NOT NULL,
    price numeric(19,4) NOT NULL,
    change_rate numeric(9,4),
    fetched_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_market_instruments_symbol UNIQUE (symbol)
);

CREATE TABLE public.market_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id bigint NOT NULL,
    price_date date NOT NULL,
    close_price numeric(19,4) NOT NULL,
    CONSTRAINT fk_market_history_instrument
        FOREIGN KEY (instrument_id) REFERENCES public.market_instruments(id) ON DELETE CASCADE,
    CONSTRAINT uk_market_history_instrument_date UNIQUE (instrument_id, price_date)
);

ALTER TABLE ONLY public.alerts
    ADD CONSTRAINT alerts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_external_id_key UNIQUE (external_id);

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.portfolio_holdings
    ADD CONSTRAINT portfolio_holdings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.portfolios
    ADD CONSTRAINT portfolios_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_keycloak_id_key UNIQUE (keycloak_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.watchlist
    ADD CONSTRAINT watchlist_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.watchlist
    ADD CONSTRAINT watchlist_user_id_instrument_code_key UNIQUE (user_id, instrument_code);

CREATE INDEX idx_news_category ON public.news USING btree (category);
CREATE INDEX idx_news_importance_score ON public.news USING btree (importance_score);
CREATE INDEX idx_news_provider ON public.news USING btree (provider);
CREATE INDEX idx_news_published_at ON public.news USING btree (published_at);
CREATE INDEX idx_news_region_scope ON public.news USING btree (region_scope);
CREATE INDEX idx_news_related_symbol ON public.news USING btree (related_symbol);
CREATE INDEX idx_market_instruments_type ON public.market_instruments (instrument_type);
CREATE INDEX idx_market_history_instrument_date ON public.market_history (instrument_id, price_date);

ALTER TABLE ONLY public.portfolios
    ADD CONSTRAINT fk9xt36kgm9cxsf79r2me0d9f6u FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.watchlist
    ADD CONSTRAINT fkden7i83qo2swnr5br4wgc5r7j FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.portfolio_holdings
    ADD CONSTRAINT fkjqi58yu3nyok2j2k3h7wd84r8 FOREIGN KEY (portfolio_id) REFERENCES public.portfolios(id);

ALTER TABLE ONLY public.alerts
    ADD CONSTRAINT fkqx4kjyy8qmc38cpa1pj5gp74i FOREIGN KEY (user_id) REFERENCES public.users(id);

INSERT INTO public.market_instruments (symbol, display_name, instrument_type, source, currency, price, change_rate, fetched_at)
VALUES
    ('BTCUSDT', 'Bitcoin', 'CRYPTO', 'BINANCE', 'USD', 103250.0000, 2.8400, TIMESTAMP '2026-05-09 10:15:00'),
    ('ETHUSDT', 'Ethereum', 'CRYPTO', 'BINANCE', 'USD', 4980.0000, 1.7600, TIMESTAMP '2026-05-09 10:15:00'),
    ('GARAN', 'Garanti BBVA', 'STOCK', 'BIST', 'TRY', 128.4000, -0.8500, TIMESTAMP '2026-05-09 10:15:00'),
    ('THYAO', 'Turkish Airlines', 'STOCK', 'BIST', 'TRY', 342.7500, 1.1200, TIMESTAMP '2026-05-09 10:15:00'),
    ('USDTRY', 'US Dollar / Turkish Lira', 'FOREX', 'TCMB', 'TRY', 38.4200, 0.2700, TIMESTAMP '2026-05-09 10:15:00'),
    ('EURTRY', 'Euro / Turkish Lira', 'FOREX', 'TCMB', 'TRY', 41.2800, 0.1900, TIMESTAMP '2026-05-09 10:15:00'),
    ('AFT', 'AFT Growth Fund', 'FUND', 'TEFAS', 'TRY', 12.4800, 0.6300, TIMESTAMP '2026-05-09 10:15:00'),
    ('TI2', 'TI2 Balanced Fund', 'FUND', 'TEFAS', 'TRY', 7.9600, -0.1800, TIMESTAMP '2026-05-09 10:15:00'),
    ('TUFE', 'Tufe Endeksi', 'MACRO_INDICATOR', 'EVDS', 'INDEX', 2650.0000, 1.0400, TIMESTAMP '2026-05-09 10:15:00'),
    ('POLICY_RATE', 'Policy Rate', 'MACRO_INDICATOR', 'EVDS', 'PERCENT', 46.0000, 0.0000, TIMESTAMP '2026-05-09 10:15:00');

INSERT INTO public.market_history (instrument_id, price_date, close_price)
SELECT instrument.id,
       series.price_date,
       ROUND(series.price_value::numeric, 4)
FROM public.market_instruments instrument
CROSS JOIN LATERAL (
    SELECT generated_date::date AS price_date,
           CASE instrument.symbol
               WHEN 'BTCUSDT' THEN 78250 + (day_no * 160) + (sin(day_no / 7.0) * 1900)
               WHEN 'ETHUSDT' THEN 3150 + (day_no * 11) + (sin(day_no / 9.0) * 170)
               WHEN 'GARAN' THEN 94 + (day_no * 0.18) + (sin(day_no / 8.0) * 2.9)
               WHEN 'THYAO' THEN 242 + (day_no * 0.52) + (sin(day_no / 10.0) * 5.7)
               WHEN 'USDTRY' THEN 33.4 + (day_no * 0.024) + (sin(day_no / 12.0) * 0.14)
               WHEN 'EURTRY' THEN 35.9 + (day_no * 0.029) + (sin(day_no / 11.0) * 0.17)
               WHEN 'AFT' THEN 9.1 + (day_no * 0.019) + (sin(day_no / 13.0) * 0.08)
               WHEN 'TI2' THEN 6.4 + (day_no * 0.011) + (sin(day_no / 14.0) * 0.05)
           END AS price_value
    FROM (
        SELECT generated_date,
               ROW_NUMBER() OVER (ORDER BY generated_date) - 1 AS day_no
        FROM generate_series(DATE '2025-01-01', DATE '2026-05-09', INTERVAL '1 day') generated_date
    ) days
) series
WHERE instrument.instrument_type <> 'MACRO_INDICATOR';

INSERT INTO public.market_history (instrument_id, price_date, close_price)
SELECT instrument.id,
       series.price_date,
       ROUND(series.price_value::numeric, 4)
FROM public.market_instruments instrument
CROSS JOIN LATERAL (
    SELECT generated_date::date AS price_date,
           CASE instrument.symbol
               WHEN 'TUFE' THEN 1985 + (month_no * 28) + (sin(month_no / 2.4) * 18)
               WHEN 'POLICY_RATE' THEN 36 + (month_no * 0.35) + (cos(month_no / 3.0) * 1.2)
           END AS price_value
    FROM (
        SELECT generated_date,
               ROW_NUMBER() OVER (ORDER BY generated_date) - 1 AS month_no
        FROM generate_series(DATE '2024-01-01', DATE '2026-05-01', INTERVAL '1 month') generated_date
    ) months
) series
WHERE instrument.instrument_type = 'MACRO_INDICATOR';
