CREATE TABLE public.alerts (
                               target_price numeric(19,4) NOT NULL,
                               created_at timestamp(6) without time zone NOT NULL,
                               id bigint NOT NULL,
                               triggered_at timestamp(6) without time zone,
                               user_id bigint NOT NULL,
                               condition_type character varying(255) NOT NULL,
                               instrument_code character varying(255) NOT NULL,
                               status character varying(255) NOT NULL,
                               CONSTRAINT alerts_condition_type_check CHECK (((condition_type)::text = ANY ((ARRAY['ABOVE'::character varying, 'BELOW'::character varying])::text[]))),
                               CONSTRAINT alerts_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'TRIGGERED'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE public.alerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.market_data_backfill_status (
                                                    fetched_count integer,
                                                    max_date date,
                                                    min_date date,
                                                    retry_count integer NOT NULL,
                                                    saved_count integer,
                                                    created_at timestamp(6) with time zone NOT NULL,
                                                    id bigint NOT NULL,
                                                    last_attempt_at timestamp(6) with time zone,
                                                    last_success_at timestamp(6) with time zone,
                                                    updated_at timestamp(6) with time zone NOT NULL,
                                                    status character varying(20) NOT NULL,
                                                    provider_source character varying(50) NOT NULL,
                                                    symbol character varying(50) NOT NULL,
                                                    last_error_message character varying(2000),
                                                    CONSTRAINT market_data_backfill_status_provider_source_check CHECK (((provider_source)::text = ANY ((ARRAY['EVDS'::character varying, 'BINANCE'::character varying, 'BIST'::character varying, 'UNKNOWN'::character varying])::text[])))
);

ALTER TABLE public.market_data_backfill_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.market_data_backfill_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.market_history (
                                       close_price numeric(19,6) NOT NULL,
                                       price_date date NOT NULL,
                                       created_at timestamp(6) with time zone NOT NULL,
                                       id bigint NOT NULL,
                                       currency character varying(20),
                                       instrument_type character varying(50) NOT NULL,
                                       source character varying(50) NOT NULL,
                                       symbol character varying(50) NOT NULL,
                                       display_name character varying(255),
                                       CONSTRAINT market_history_instrument_type_check CHECK (((instrument_type)::text = ANY ((ARRAY['CURRENCY'::character varying, 'FX'::character varying, 'GOLD'::character varying, 'STOCK'::character varying, 'FUND'::character varying, 'VIOP'::character varying, 'IPO'::character varying, 'CRYPTO'::character varying, 'INDEX'::character varying, 'COMMODITY'::character varying, 'UNKNOWN'::character varying])::text[]))),
                                       CONSTRAINT market_history_source_check CHECK (((source)::text = ANY ((ARRAY['EVDS'::character varying, 'BINANCE'::character varying, 'BIST'::character varying, 'UNKNOWN'::character varying])::text[])))
);

ALTER TABLE public.market_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.market_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.market_instruments (
                                           active boolean NOT NULL,
                                           created_at timestamp(6) with time zone NOT NULL,
                                           id bigint NOT NULL,
                                           updated_at timestamp(6) with time zone NOT NULL,
                                           currency character varying(20),
                                           instrument_type character varying(50) NOT NULL,
                                           symbol character varying(50) NOT NULL,
                                           name character varying(255) NOT NULL,
                                           CONSTRAINT market_instruments_instrument_type_check CHECK (((instrument_type)::text = ANY ((ARRAY['CURRENCY'::character varying, 'FX'::character varying, 'GOLD'::character varying, 'STOCK'::character varying, 'FUND'::character varying, 'VIOP'::character varying, 'IPO'::character varying, 'CRYPTO'::character varying, 'INDEX'::character varying, 'COMMODITY'::character varying, 'UNKNOWN'::character varying])::text[])))
);

ALTER TABLE public.market_instruments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.market_instruments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.market_provider_mappings (
                                                 enabled boolean NOT NULL,
                                                 priority integer NOT NULL,
                                                 refresh_interval_seconds integer,
                                                 created_at timestamp(6) with time zone NOT NULL,
                                                 id bigint NOT NULL,
                                                 instrument_id bigint NOT NULL,
                                                 updated_at timestamp(6) with time zone NOT NULL,
                                                 provider_source character varying(50) NOT NULL,
                                                 provider_symbol character varying(100) NOT NULL,
                                                 CONSTRAINT market_provider_mappings_provider_source_check CHECK (((provider_source)::text = ANY ((ARRAY['EVDS'::character varying, 'BINANCE'::character varying, 'BIST'::character varying, 'UNKNOWN'::character varying])::text[])))
);

ALTER TABLE public.market_provider_mappings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.market_provider_mappings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.news (
                             importance_score integer NOT NULL,
                             created_at timestamp(6) without time zone NOT NULL,
                             id bigint NOT NULL,
                             published_at timestamp(6) without time zone,
                             updated_at timestamp(6) without time zone NOT NULL,
                             language character varying(10),
                             region_scope character varying(20) NOT NULL,
                             related_symbol character varying(30),
                             category character varying(100),
                             provider character varying(100) NOT NULL,
                             source character varying(100) NOT NULL,
                             external_id character varying(200) NOT NULL,
                             title character varying(500) NOT NULL,
                             url character varying(1200) NOT NULL,
                             image_url text,
                             summary text
);

ALTER TABLE public.news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.portfolio_holdings (
                                           buy_price numeric(19,4) NOT NULL,
                                           quantity numeric(19,4) NOT NULL,
                                           created_at timestamp(6) without time zone NOT NULL,
                                           id bigint NOT NULL,
                                           portfolio_id bigint NOT NULL,
                                           updated_at timestamp(6) without time zone NOT NULL,
                                           instrument_code character varying(255) NOT NULL
);

ALTER TABLE public.portfolio_holdings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolio_holdings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.portfolios (
                                   created_at timestamp(6) without time zone NOT NULL,
                                   id bigint NOT NULL,
                                   user_id bigint NOT NULL,
                                   visibility_status character varying(30) NOT NULL,
                                   portfolio_name character varying(255) NOT NULL
);

ALTER TABLE public.portfolios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.users (
                              active boolean NOT NULL,
                              created_at timestamp(6) without time zone NOT NULL,
                              id bigint NOT NULL,
                              last_login_at timestamp(6) without time zone,
                              updated_at timestamp(6) without time zone NOT NULL,
                              role character varying(20) NOT NULL,
                              email character varying(255) NOT NULL,
                              full_name character varying(255) NOT NULL,
                              keycloak_id character varying(255),
                              preferred_language character varying(255),
                              theme_preference character varying(255),
                              CONSTRAINT users_preferred_language_check CHECK (((preferred_language)::text = ANY ((ARRAY['TR'::character varying, 'EN'::character varying])::text[]))),
                              CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[]))),
                              CONSTRAINT users_theme_preference_check CHECK (((theme_preference)::text = ANY ((ARRAY['LIGHT'::character varying, 'DARK'::character varying, 'SYSTEM'::character varying])::text[])))
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.watchlist (
                                  created_at timestamp(6) without time zone NOT NULL,
                                  id bigint NOT NULL,
                                  user_id bigint NOT NULL,
                                  instrument_code character varying(255) NOT NULL
);

ALTER TABLE public.watchlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watchlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

ALTER TABLE ONLY public.alerts
    ADD CONSTRAINT alerts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.market_data_backfill_status
    ADD CONSTRAINT market_data_backfill_status_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.market_history
    ADD CONSTRAINT market_history_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.market_instruments
    ADD CONSTRAINT market_instruments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.market_provider_mappings
    ADD CONSTRAINT market_provider_mappings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_external_id_key UNIQUE (external_id);

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.portfolio_holdings
    ADD CONSTRAINT portfolio_holdings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.portfolios
    ADD CONSTRAINT portfolios_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.market_data_backfill_status
    ADD CONSTRAINT uk_market_backfill_status_provider_symbol UNIQUE (provider_source, symbol);

ALTER TABLE ONLY public.market_history
    ADD CONSTRAINT uk_market_history_symbol_source_date UNIQUE (symbol, source, price_date);

ALTER TABLE ONLY public.market_instruments
    ADD CONSTRAINT uk_market_instruments_symbol UNIQUE (symbol);

ALTER TABLE ONLY public.market_provider_mappings
    ADD CONSTRAINT uk_market_provider_mappings_source_symbol UNIQUE (provider_source, provider_symbol);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_keycloak_id_key UNIQUE (keycloak_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.watchlist
    ADD CONSTRAINT watchlist_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.watchlist
    ADD CONSTRAINT watchlist_user_id_instrument_code_key UNIQUE (user_id, instrument_code);

CREATE INDEX idx_market_history_price_date ON public.market_history USING btree (price_date);
CREATE INDEX idx_market_history_source ON public.market_history USING btree (source);
CREATE INDEX idx_market_history_symbol ON public.market_history USING btree (symbol);
CREATE INDEX idx_market_history_symbol_price_date ON public.market_history USING btree (symbol, price_date);
CREATE INDEX idx_market_instruments_active ON public.market_instruments USING btree (active);
CREATE INDEX idx_market_provider_mappings_instrument_id ON public.market_provider_mappings USING btree (instrument_id);
CREATE INDEX idx_market_provider_mappings_source_enabled_priority ON public.market_provider_mappings USING btree (provider_source, enabled, priority);
CREATE INDEX idx_news_category ON public.news USING btree (category);
CREATE INDEX idx_news_importance_score ON public.news USING btree (importance_score);
CREATE INDEX idx_news_provider ON public.news USING btree (provider);
CREATE INDEX idx_news_published_at ON public.news USING btree (published_at);
CREATE INDEX idx_news_region_scope ON public.news USING btree (region_scope);
CREATE INDEX idx_news_related_symbol ON public.news USING btree (related_symbol);

ALTER TABLE ONLY public.portfolios
    ADD CONSTRAINT fk9xt36kgm9cxsf79r2me0d9f6u FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.market_provider_mappings
    ADD CONSTRAINT fk_market_provider_mappings_instrument FOREIGN KEY (instrument_id) REFERENCES public.market_instruments(id);

ALTER TABLE ONLY public.watchlist
    ADD CONSTRAINT fkden7i83qo2swnr5br4wgc5r7j FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.portfolio_holdings
    ADD CONSTRAINT fkjqi58yu3nyok2j2k3h7wd84r8 FOREIGN KEY (portfolio_id) REFERENCES public.portfolios(id);

ALTER TABLE ONLY public.alerts
    ADD CONSTRAINT fkqx4kjyy8qmc38cpa1pj5gp74i FOREIGN KEY (user_id) REFERENCES public.users(id);

