CREATE TABLE public.premium_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    status character varying(32) NOT NULL,
    process_instance_id bigint,
    requested_at timestamp(6) without time zone NOT NULL,
    activated_at timestamp(6) without time zone,
    cancelled_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT premium_subscriptions_status_check CHECK (((status)::text = ANY ((ARRAY[
        'PREMIUM_REQUESTED'::character varying,
        'PAYMENT_PENDING'::character varying,
        'PAYMENT_FAILED'::character varying,
        'ACTIVE'::character varying,
        'CANCELLED'::character varying
    ])::text[])))
);

CREATE INDEX idx_premium_subscriptions_user_created_at
    ON public.premium_subscriptions (user_id, created_at DESC);

CREATE INDEX idx_premium_subscriptions_status
    ON public.premium_subscriptions (status);

ALTER TABLE ONLY public.premium_subscriptions
    ADD CONSTRAINT fk_premium_subscriptions_user
    FOREIGN KEY (user_id) REFERENCES public.users(id);
