CREATE TABLE market_data_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    instrument_type VARCHAR(50) NOT NULL,
    price NUMERIC(19, 8) NOT NULL,
    change_amount NUMERIC(19, 8),
    change_percent NUMERIC(19, 8),
    currency VARCHAR(20),
    price_time TIMESTAMP WITHOUT TIME ZONE,
    fetched_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    source VARCHAR(100) NOT NULL
);

CREATE INDEX idx_market_data_snapshots_symbol_fetched_at
    ON market_data_snapshots(symbol, fetched_at);

CREATE INDEX idx_market_data_snapshots_instrument_type
    ON market_data_snapshots(instrument_type);
