DROP TABLE IF EXISTS public.market_history;
DROP TABLE IF EXISTS public.market_prices;
DROP TABLE IF EXISTS public.market_instruments;

CREATE TABLE public.market_instruments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_code character varying(100) NOT NULL,
    instrument_name character varying(255) NOT NULL,
    instrument_type character varying(30) NOT NULL,
    source_name character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_market_instrument_code_source_name UNIQUE (instrument_code, source_name)
);
