CREATE TABLE public.market_prices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id bigint NOT NULL,
    price_value numeric(19,4) NOT NULL,
    price_timestamp timestamp(6) without time zone NOT NULL,
    source_name character varying(50) NOT NULL,
    CONSTRAINT fk_market_prices_instrument
        FOREIGN KEY (instrument_id) REFERENCES public.market_instruments(id)
);
