CREATE TABLE market_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    title VARCHAR(500) NOT NULL,
    symbol VARCHAR(50),
    issuer_code VARCHAR(50),
    published_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    url VARCHAR(1200),
    summary TEXT,
    raw_payload TEXT,
    fetched_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_market_events_symbol_published_at
    ON market_events(symbol, published_at);

CREATE INDEX idx_market_events_source_event_type
    ON market_events(source, event_type);
