CREATE TABLE portfolio_holdings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    instrument_code VARCHAR(255) NOT NULL,
    quantity NUMERIC(19, 4) NOT NULL,
    buy_price NUMERIC(19, 4) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_portfolio_holdings_portfolio FOREIGN KEY (portfolio_id) REFERENCES portfolios (id),
    CONSTRAINT uk_portfolio_holdings_portfolio_instrument UNIQUE (portfolio_id, instrument_code)
);
