spring:
  profiles:
    default: local

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/financeportaldb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/finance-portal}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/finance-portal/protocol/openid-connect/certs}

logging:
  level:
    com.emrehalli.financeportal.market: INFO
    com.emrehalli.financeportal.market.provider.evds: DEBUG
    com.emrehalli.financeportal.news.provider.finnhub.client: DEBUG
    com.emrehalli.financeportal.news.provider.bloomberght: DEBUG

market:
  providers:
    binance:
      enabled: true
      base-url: https://api.binance.com
      symbols:
        - BTCUSDT
        - ETHUSDT
        - BNBUSDT
        - SOLUSDT
        - XRPUSDT
        - ADAUSDT
        - AVAXUSDT
        - DOGEUSDT
    tefas:
      enabled: true
      base-url: https://www.tefas.gov.tr
      symbols:
        - AFT
        - IIH
        - TCD
        - IPB
        - MAC
    evds:
      enabled: true
      api:
        key: Rb7ROmhyOC
        url: https://evds3.tcmb.gov.tr/igmevdsms-dis
      history:
        scheduler-lookback-days: 7
        backfill-default-days: 365

      series:
        - evdsKey: TP_DK_USD_A
          apiCode: TP.DK.USD.A
          symbol: USDTRY
          name: USD / TRY
          instrumentType: FX
          currency: TRY

        - evdsKey: TP_DK_EUR_A
          apiCode: TP.DK.EUR.A
          symbol: EURTRY
          name: EUR / TRY
          instrumentType: FX
          currency: TRY

        - evdsKey: TP_DK_GBP_A
          apiCode: TP.DK.GBP.A
          symbol: GBPTRY
          name: GBP / TRY
          instrumentType: FX
          currency: TRY

        - evdsKey: TP_DK_AUD_A_YTL
          apiCode: TP.DK.AUD.A.YTL
          symbol: AUDTRY
          name: AUD / TRY
          instrumentType: FX
          currency: TRY

        - evdsKey: TP_DK_CNY_A_YTL
          apiCode: TP.DK.CNY.A.YTL
          symbol: CNYTRY
          name: CNY / TRY
          instrumentType: FX
          currency: TRY

        - evdsKey: TP_DK_CHF_A
          apiCode: TP.DK.CHF.A
          symbol: CHFTRY
          name: CHF / TRY
          instrumentType: FX
          currency: TRY

        - evdsKey: TP_DK_JPY_A
          apiCode: TP.DK.JPY.A
          symbol: JPYTRY
          name: JPY / TRY
          instrumentType: FX
          currency: TRY

  refresh:
    initial-delay-ms: 0
    scheduler-delay-ms: 300000
    providers:
      binance:
        enabled: true
        refresh-minutes: 1
      tefas:
        enabled: true
        refresh-minutes: 1440
      evds:
        enabled: true
        refresh-minutes: 15


finnhub:
  enabled: true
  api:
    url: https://finnhub.io/api/v1
    key: ${FINNHUB_API_KEY:}
  sync:
    default-days-back: 3

bloomberght:
  api:
    url: https://www.bloomberght.com/
