spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/financeportaldb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.emrehalli.financeportal.market.provider.tcmb.client: DEBUG
    com.emrehalli.financeportal.news.provider.finnhub.client: DEBUG
    com.emrehalli.financeportal.news.provider.bloomberght: DEBUG

evds:
  api:
    key: Rb7ROmhyOC
    url: https://evds3.tcmb.gov.tr/igmevdsms-dis

finnhub:
  api:
    key: d7f7hshr01qpjqqjo6v0d7f7hshr01qpjqqjo6vg
    url: https://finnhub.io/api/v1
  sync:
    default-days-back: 3

bloomberght:
  api:
    url: https://www.bloomberght.com/